version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Antlr4BuildTasks"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
      - "target:csharp-standard"
